Update types.py
Pydantic Error:

pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `preserve_init_image_color_profile = False`. All model fields require a type annotation; if `preserve_init_image_color_profile` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.